name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup project path
      run: godot --path project.godot
    - name: Run game
      run: godot
